version: "3.8"

services:

  application:
    image: "node:18.16-alpine"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.application.rule=Host(`application.my-project.localhost`)"
      - "traefik.http.services.application.loadbalancer.server.port=3000"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - "./src:/usr/local/src"
    networks:
      - "my-project-proxy"
      - "my-project-application"
    working_dir: "/usr/local/src"

networks:
  my-project-proxy:
    name: "my-project-proxy"
    external: true
  my-project-application:
    name: "my-project-application"
