version: "3.8"

services:

  proxy:
    image: "traefik:2.9"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`my-project.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "my-project-proxy"
    command:
      - "--api.insecure=true"
      - "--entrypoints.http.address=:80"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=my-project-proxy"
      - "--providers.docker.exposedbydefault=false"

networks:
  my-project-proxy:
    name: "my-project-proxy"
