version: "3.8"

services:

  prometheus:
    image: "quay.io/prometheus/prometheus:v2.43.0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.my-project.localhost`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - "my-project-proxy"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro"
      - "./rules:/etc/prometheus/rules:ro"
    command:
      - "--config.file"
      - "/etc/prometheus/prometheus.yaml"

  alertmanager:
    image: "quay.io/prometheus/alertmanager:v0.25.0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.my-project.localhost`)"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
    networks:
      - "my-project-proxy"
    volumes:
      - "./alertmanager.yaml:/etc/alertmanager/alertmanager.yaml:ro"
    command:
      - "--config.file"
      - "/etc/alertmanager/alertmanager.yaml"

networks:
  my-project-proxy:
    name: "my-project-proxy"
    external: true
