scrape_configs:
- job_name: "application"
  scrape_interval: "1s"
  static_configs:
  - targets:
    - "application:3000"

rule_files:
  - "/etc/prometheus/rules/*.yaml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
